
server:
      port: 9000 
spring:
  application:
    name: gateway
  cloud:
    gateway:
     boot:
       admin:
        client:
        url: http://localhost:1111/
     routes:
      - id: CreditManager
        uri: lb://CreditManager
        predicates:
        - Path=/getCreditmanager
            
#            routes:
#             - id: CreditManager
#                uri:lb://CreditManager
#            predicate:
#               - path= /getCreditmanager
              
            
      